/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp 14
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int nf, nc;

    public Principal() {
        initComponents();
        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdLlenarManual, cmdLlenarAutomatico, cmdRecorridoUno,
            cmdRecorridoDos, cmdRecorridoTres, cmdRecorridoCuatro, cmdRecorridoCinco};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdRecorridoUno = new javax.swing.JButton();
        cmdRecorridoDos = new javax.swing.JButton();
        cmdRecorridoTres = new javax.swing.JButton();
        cmdRecorridoCuatro = new javax.swing.JButton();
        cmdRecorridoCinco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumerodeFilas = new javax.swing.JTextField();
        txtNumerodeColumnas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdLimpiar = new javax.swing.JButton();
        cmdLlenarAutomatico = new javax.swing.JButton();
        cmdLlenarManual = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECORRIDOS CON MATRICES");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdRecorridoUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridouno.png"))); // NOI18N
        cmdRecorridoUno.setBorder(null);
        cmdRecorridoUno.setBorderPainted(false);
        cmdRecorridoUno.setContentAreaFilled(false);
        cmdRecorridoUno.setFocusable(false);
        cmdRecorridoUno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridouno1.png"))); // NOI18N
        cmdRecorridoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoUnoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRecorridoUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 190, 170));

        cmdRecorridoDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridodos.png"))); // NOI18N
        cmdRecorridoDos.setBorder(null);
        cmdRecorridoDos.setBorderPainted(false);
        cmdRecorridoDos.setContentAreaFilled(false);
        cmdRecorridoDos.setFocusable(false);
        cmdRecorridoDos.setLabel("");
        cmdRecorridoDos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridodos1.0.png"))); // NOI18N
        cmdRecorridoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoDosActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRecorridoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 200, 170));

        cmdRecorridoTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridotres.png"))); // NOI18N
        cmdRecorridoTres.setBorder(null);
        cmdRecorridoTres.setBorderPainted(false);
        cmdRecorridoTres.setContentAreaFilled(false);
        cmdRecorridoTres.setFocusable(false);
        cmdRecorridoTres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorridotres1.png"))); // NOI18N
        cmdRecorridoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoTresActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRecorridoTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 210, 180));

        cmdRecorridoCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorrido4.png"))); // NOI18N
        cmdRecorridoCuatro.setBorder(null);
        cmdRecorridoCuatro.setBorderPainted(false);
        cmdRecorridoCuatro.setContentAreaFilled(false);
        cmdRecorridoCuatro.setFocusable(false);
        cmdRecorridoCuatro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorrido4.1.png"))); // NOI18N
        cmdRecorridoCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoCuatroActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRecorridoCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 210, 170));

        cmdRecorridoCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorrido5.png"))); // NOI18N
        cmdRecorridoCinco.setBorder(null);
        cmdRecorridoCinco.setBorderPainted(false);
        cmdRecorridoCinco.setContentAreaFilled(false);
        cmdRecorridoCinco.setFocusable(false);
        cmdRecorridoCinco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recorrido5.1.png"))); // NOI18N
        cmdRecorridoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoCincoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRecorridoCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, -1, 170));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("RECORRIDOS CON MATRICES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("N° Filas :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel2.add(txtNumerodeFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 30, -1));
        jPanel2.add(txtNumerodeColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 30, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("N° Columnas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 410, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        cmdLimpiar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cmdLimpiar.setForeground(new java.awt.Color(240, 240, 240));
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        cmdLlenarAutomatico.setBackground(new java.awt.Color(0, 0, 0));
        cmdLlenarAutomatico.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cmdLlenarAutomatico.setForeground(new java.awt.Color(240, 240, 240));
        cmdLlenarAutomatico.setText("Automatico");
        cmdLlenarAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenarAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        cmdLlenarManual.setBackground(new java.awt.Color(0, 0, 0));
        cmdLlenarManual.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cmdLlenarManual.setForeground(new java.awt.Color(240, 240, 240));
        cmdLlenarManual.setText("Manual");
        cmdLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        cmdCrear.setBackground(new java.awt.Color(0, 0, 0));
        cmdCrear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(240, 240, 240));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 460, 70));

        tblTablaInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 350, 230));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane3.setViewportView(txtResultado);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 560, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 630, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        DefaultTableModel tm;
        if (txtNumerodeFilas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite El Numero De Filas ", 2);
            txtNumerodeFilas.requestFocusInWindow();
        } else if (txtNumerodeColumnas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite El Numero De Columnas ", 2);
            txtNumerodeColumnas.requestFocusInWindow();
        } else {
            nf = Integer.parseInt(txtNumerodeFilas.getText());
            nc = Integer.parseInt(txtNumerodeColumnas.getText());
            if (nf == 0) {
                Helper.mensaje(this, "Numero De Filas No Puede Ser Cero", 3);
                txtNumerodeFilas.requestFocusInWindow();
            } else if (nc == 0) {
                Helper.mensaje(this, "Numero De Columnas No Puede Ser Cero", 3);
                txtNumerodeColumnas.requestFocusInWindow();
            } else if (nc > 13) {
                Helper.mensaje(this, "El Numero De Columnas No Puede Ser Mayor A 13", 2);
                txtNumerodeColumnas.requestFocusInWindow();
            } else {
                tm = (DefaultTableModel) tblTablaInicial.getModel();
                tm.setRowCount(nf);
                tm.setColumnCount(nc);
                JButton botonesH[] = {cmdLlenarManual, cmdLlenarAutomatico, cmdLimpiar};
                JButton botonesD[] = {cmdCrear};
                Helper.habilitarBotones(botonesH);
                Helper.deshabilitarBotones(botonesD);
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarManualActionPerformed
        int nf, nc, n;
        int sw, res;
        boolean aux = true;
        nf = tblTablaInicial.getRowCount();
        nc = tblTablaInicial.getColumnCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elemento en la posicion[" + i + "] " + " [" + j + "]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un numero valido", 2);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;
                            aux = false;
                            JButton botonesH[] = {cmdCrear, cmdLimpiar};
                            Helper.habilitarBotones(botonesH);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[] = {cmdRecorridoUno, cmdRecorridoDos, cmdRecorridoTres, cmdRecorridoCuatro, cmdRecorridoCinco};
        JButton botonesD[] = {cmdLlenarManual, cmdLlenarAutomatico};
        Helper.deshabilitarBotones(botonesD);
        Helper.habilitarBotones(botonesH, aux);
    }//GEN-LAST:event_cmdLlenarManualActionPerformed

    private void cmdLlenarAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAutomaticoActionPerformed
        int nf, nc, n;
        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
        }
        JButton botonesH[] = {cmdLimpiar, cmdRecorridoUno, cmdRecorridoDos, cmdRecorridoTres, cmdRecorridoCuatro, cmdRecorridoCinco};
        JButton botonesD[] = {cmdCrear, cmdLlenarManual, cmdLlenarAutomatico};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenarAutomaticoActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtNumerodeFilas.setText("");
        txtNumerodeColumnas.setText("");
        txtNumerodeFilas.requestFocusInWindow();
        txtResultado.setText("");
        Helper.porDefectoTabla(tblTablaInicial);
        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdLlenarManual, cmdLlenarAutomatico, cmdRecorridoUno,
            cmdRecorridoDos, cmdRecorridoTres, cmdRecorridoCuatro, cmdRecorridoCinco};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdRecorridoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoUnoActionPerformed
        if (nf != nc) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Deben Ser Iguales", 2);
        } else if (nf < 5 || nf > 13) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Debe Ser Mayor o Igual a 5 Y Menor O Igual A 13", 2);
        } else {
            txtResultado.setText(Helper.recorridoUno(tblTablaInicial));
        }
    }//GEN-LAST:event_cmdRecorridoUnoActionPerformed

    private void cmdRecorridoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoDosActionPerformed
        if (nf != nc) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Deben Ser Iguales", 2);
        } else if (nf < 5 || nf > 13) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Debe Ser Mayor o Igual a 5 Y Menor O Igual A 13", 2);
        } else {
            txtResultado.setText(Helper.recorridoDos(tblTablaInicial));
        }
    }//GEN-LAST:event_cmdRecorridoDosActionPerformed

    private void cmdRecorridoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoTresActionPerformed
        //txtResultado.setText(Helper.recorridoTres(tblTablaInicial));
    }//GEN-LAST:event_cmdRecorridoTresActionPerformed

    private void cmdRecorridoCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoCuatroActionPerformed
        if (nf != nc) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Deben Ser Iguales", 2);
        } else if (nf < 5 || nf > 13) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Debe Ser Mayor o Igual a 5 Y Menor O Igual A 13", 2);
        } else {
            txtResultado.setText(Helper.recorridoCuatro(tblTablaInicial));
        }
    }//GEN-LAST:event_cmdRecorridoCuatroActionPerformed

    private void cmdRecorridoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoCincoActionPerformed
        if (nf != nc) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Deben Ser Iguales", 2);
        } else if (nf < 5 || nf > 13) {
            Helper.mensaje(this, "Para Que Todos Los Recorridos Se Den \n"
                    + "El Numero De Filas Y Columnas Debe Ser Mayor o Igual a 5 Y Menor O Igual A 13", 2);
        } else if (nf % 2 == 0) {
            Helper.mensaje(this, "Para Que Este Recorrido Se De El Numero De Filas Y Columnas Deben Ser Impares", 2);
        } else {
            txtResultado.setText(Helper.recorridoCinco(tblTablaInicial));
        }
    }//GEN-LAST:event_cmdRecorridoCincoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenarAutomatico;
    private javax.swing.JButton cmdLlenarManual;
    private javax.swing.JButton cmdRecorridoCinco;
    private javax.swing.JButton cmdRecorridoCuatro;
    private javax.swing.JButton cmdRecorridoDos;
    private javax.swing.JButton cmdRecorridoTres;
    private javax.swing.JButton cmdRecorridoUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTextField txtNumerodeColumnas;
    private javax.swing.JTextField txtNumerodeFilas;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
